2025-06-13 03:12:19,000 [ERROR] Failed to backup: [Errno 17] File exists: 'devops-Backup: 13-06-2025'
2025-06-13 03:12:20,120 [INFO] Backup committed and pushed to GitHub successfully.
2025-06-13 03:13:32,322 [INFO] Backup completed: devops-Backup: 13-06-2025
2025-06-13 03:13:33,453 [INFO] Backup committed and pushed to GitHub successfully.
2025-06-13 03:14:22,309 [INFO] Backup completed: devops/python-Backup: 13-06-2025
2025-06-13 03:14:26,251 [INFO] Backup committed and pushed to GitHub successfully.
2025-06-13 03:17:31,458 [ERROR] Failed to backup: [Errno 17] File exists: 'devops/python-Backup: 13-06-2025'
